services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    container_name: app_backend
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/todo_db
  websocket:
    container_name: app_websocket
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: .
      dockerfile: docker/Dockerfile.ws
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/todo_db
  web:
    container_name: app_web
    depends_on:
      postgres:
        condition: service_healthy

    build:
      context: .
      dockerfile: docker/Dockerfile.web
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/todo_db