FROM oven/bun:latest

WORKDIR /app
RUN apt-get update -y && apt-get install -y openssl

COPY package*.json bun.lock turbo.json ./
COPY ./packages ./packages
RUN bun install && bun add express @types/express && bun add prisma @prisma/client

COPY ./apps/backend ./apps/backend

RUN bun run db:generate


EXPOSE 8080

CMD ["sh", "-c", "bun run db:migrate && bun run db:generate && bun run start:backend"]
