FROM oven/bun:latest

WORKDIR /app
RUN apt-get update -y && apt-get install -y openssl

COPY package*.json bun.lock turbo.json ./
COPY ./packages ./packages
RUN bun install

COPY ./apps/backend ./apps/backend

RUN bun run db:generate
RUN bun run build

EXPOSE 8080

CMD ["sh", "-c", "bun run db:migrate && bun run start:backend"]