name: Deploy the Backend

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: |
            ${{secrets.DOCKERHUB_USERNAME}}/sample_backend:latest
            ${{secrets.DOCKERHUB_USERNAME}}/sample_backend:${{ github.run_number }}
      - name: Deploy to the vm
        run: |
          echo "Deploying to the vm"
          echo "${{secrets.SSH_PRIVATE_KEY}}" &> ~/ssh_key
          mkdir -p /home/runner/.ssh
          chmod 600 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@${{secrets.SERVER_IP}} "
          docker pull ${{secrets.DOCKERHUB_USERNAME}}/sample_backend:latest &&
          
          if [ \$(docker ps -aq -f name=sample_backend) ]; then
            echo 'Stopping existing container...'
            docker stop sample_backend &&
            docker rm sample_backend
          else
            echo 'No existing container found, skipping stop/remove.'
          fi &&
          
          docker run -d --name sample_backend -p 8080:8080 ${{secrets.DOCKERHUB_USERNAME}}/sample_backend:latest
          "
          echo "Deployment completed"
